In [307]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [308]:
df = pd.read_csv('train.csv')
df.sample(7)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
572            1701     1          0.5         0  13       1          46   
745             894     0          2.1         1  16       0          16   
1380           1811     0          2.9         0   0       0          33   
1361           1549     1          1.5         1   0       1          27   
723            1271     0          0.5         1   2       0          54   
705            1519     0          2.9         0   2       0          30   
1590           1640     0          0.5         1   1       1          36   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
572     0.9        115        2  ...        364       828  3717    11     0   
745     0.7        168        8  ...        286      1300  3377     5     1   
1380    0.2        132        8  ...       1099      1553  2610     8     3   
1361    0.4        113        5  ...        632      1162   436    10     8   
723     0.1        159        8  ...        613       650   990    14    11   
705     0.7        112        7  ...       1122      1702  2440     9     5   
1590    0.9         87        8  ...        664      1806  3235     6     1   

      talk_time  three_g  touch_screen  wifi  price_range  
572          10        1             1     0            3  
745           6        1             1     1            2  
1380         13        1             1     0            3  
1361         11        1             0     0            0  
723           6        0             1     1            0  
705          10        1             1     1            2  
1590         10        1             0     1            3  

[7 rows x 21 columns]

In [309]:
df.isna().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [310]:
dfTest = pd.read_csv('test.csv')
dfTest.sample(7)

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
716  717           1701     1          1.6         1   2       1          53   
35    36           1175     1          2.1         0   3       0          33   
869  870            602     0          2.5         0   7       1          59   
521  522            756     0          1.0         0   0       0          33   
603  604           1334     0          1.2         1   0       0          35   
7      8            833     0          2.4         1   0       0          62   
505  506            532     0          0.5         0   7       0          51   

     m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
716    0.8         88  ...  14       1281      1776  3340    14    11   
35     0.9        124  ...   8        119      1777  1617     5     3   
869    0.3        166  ...  11         76       637  1914    11     2   
521    0.2        177  ...   3        506       573  3402    19     0   
603    0.1        199  ...   1        158       971  1038    16    14   
7      0.8        111  ...   2       1312      1880  1495     7     2   
505    0.6        180  ...  14        406      1249  1525     7     6   

     talk_time  three_g  touch_screen  wifi  
716         19        1             1     0  
35           7        0             0     1  
869         10        1             1     0  
521          3        1             1     0  
603         17        1             0     0  
7           18        0             1     1  
505          2        0             1     1  

[7 rows x 21 columns]

In [311]:
dfTest.isna().sum()

id               0
battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
dtype: int64

In [312]:
df.drop_duplicates(inplace=True)
dfTest.drop_duplicates(inplace=True)
dfTest.drop(columns='id', inplace=True)

In [313]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [314]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=42,shuffle=True)

In [315]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

In [316]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)
lrPredicted = lr.predict(x_test)

In [317]:
from sklearn.neighbors import KNeighborsClassifier
knnClass = KNeighborsClassifier(n_neighbors=5,weights='distance',metric='minkowski',algorithm='auto',p=2)
knnClass.fit(x_train,y_train)
knnPredicted = knnClass.predict(x_test)

In [318]:
from sklearn.svm import SVC
classifierSVM = SVC(kernel = 'rbf', random_state = 0)
classifierSVM.fit(x_train, y_train)
SVMPredicted = classifierSVM.predict(x_test)

In [319]:
from sklearn.naive_bayes import GaussianNB
classifierNB = GaussianNB()
classifierNB.fit(x_train, y_train)
NBpredicted = classifierNB.predict(x_test)

In [320]:
from sklearn.tree import DecisionTreeClassifier
classifierDT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, max_depth = 6, min_samples_split = 5)
classifierDT.fit(x_train, y_train)
DTpredict = classifierDT.predict(x_test)

In [321]:
from sklearn.ensemble import RandomForestClassifier
classifierRF = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0, max_depth=8, min_samples_split=5)
classifierRF.fit(x_train, y_train)
RFpredict = classifierRF.predict(x_test)

In [322]:
NewDf = pd.DataFrame({ "Actual":y_test,'Logistic': lrPredicted, 'KNN':knnPredicted,'SVM':SVMPredicted})
NewDf

Actual  Logistic  KNN  SVM
1860       0         0    0    0
353        2         2    1    2
1333       1         1    0    1
905        3         3    2    3
1289       1         1    0    1
...      ...       ...  ...  ...
965        3         3    3    3
1284       2         2    1    2
1739       1         1    1    1
261        1         1    0    1
535        2         2    2    2

[400 rows x 4 columns]

In [323]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm1 = confusion_matrix(y_test, lrPredicted)
print("The confusion matrix for logistic regression is: \n",cm1)
print("The accuracy of logistic regression is ",accuracy_score(y_test, lrPredicted)*100,"%")

The confusion matrix for logistic regression is: 
 [[101   4   0   0]
 [  0  91   0   0]
 [  0   2  87   3]
 [  0   0   1 111]]
The accuracy of logistic regression is  97.5 %


In [324]:
cm2 = confusion_matrix(y_test, knnPredicted)
print("The confusion matrix for knn is: \n",cm2)
print("The accuracy of knn is ",accuracy_score(y_test, knnPredicted)*100,"%")

The confusion matrix for knn is: 
 [[67 29  9  0]
 [19 38 27  7]
 [ 3 30 41 18]
 [ 1  4 34 73]]
The accuracy of knn is  54.75 %


In [325]:
cm3 = confusion_matrix(y_test, NBpredicted)
print("The confusion matrix for knn is: \n",cm3)
print("The accuracy of naive bayes is ",accuracy_score(y_test, NBpredicted)*100,"%")

The confusion matrix for knn is: 
 [[95 10  0  0]
 [10 62 19  0]
 [ 0  9 71 12]
 [ 0  0 21 91]]
The accuracy of naive bayes is  79.75 %


In [326]:
cm4 = confusion_matrix(y_test, SVMPredicted)
print("The confusion matrix for knn is: \n",cm4)
print("The accuracy of SVM is ",accuracy_score(y_test, SVMPredicted)*100,"%")

The confusion matrix for knn is: 
 [[ 98   7   0   0]
 [  5  81   5   0]
 [  0  13  75   4]
 [  0   0   9 103]]
The accuracy of SVM is  89.25 %


In [327]:
cm5 = confusion_matrix(y_test, DTpredict)
print("The confusion matrix for Decision Tree is: \n",cm5)
print("The accuracy of Decision Tree is ",accuracy_score(y_test, DTpredict)*100,"%")

The confusion matrix for knn is: 
 [[89 16  0  0]
 [ 6 72 13  0]
 [ 0  8 79  5]
 [ 0  0 15 97]]
The accuracy of Decision Tree is  84.25 %


In [328]:
cm6 = confusion_matrix(y_test, RFpredict)
print("The confusion matrix for Random Forest is: \n",cm6)
print("The accuracy of Random Forest is ",accuracy_score(y_test, RFpredict)*100,"%")

The confusion matrix for knn is: 
 [[ 93  12   0   0]
 [  9  73   7   2]
 [  0  13  67  12]
 [  0   0  11 101]]
The accuracy of Decision Tree is  83.5 %


In [329]:
## We will be choosing SVM for filling the values of test.csv
x_scaled = sc.fit_transform(x)
lr.fit(x_scaled,y)
newXTest = dfTest

In [330]:
newXTest_Scaled = sc.transform(newXTest)

In [331]:
FinalPredicted =  lr.predict(newXTest_Scaled)

In [332]:
FinalPredicted

array([3, 3, 2, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 2, 1, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 1, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 3, 0, 3, 0, 3, 1, 1, 3, 3, 3, 0, 1, 1, 1,
       2, 3, 1, 2, 1, 2, 2, 3, 3, 0, 2, 0, 1, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 0, 0, 3, 0, 2, 0, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 2, 3, 0, 0, 3, 2, 1, 2, 0, 3, 2, 2, 2, 0, 2,
       2, 1, 3, 1, 1, 0, 3, 2, 1, 2, 1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 1, 0,
       3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 2, 1, 0, 1,
       0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 0, 3, 1, 0, 2, 2,
       3, 3, 1, 2, 3, 2, 3, 2, 2, 1, 0, 0, 1, 3, 0, 2, 3, 3, 0, 2, 0, 3,
       2, 3, 3, 1, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 3, 1, 3, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 0, 2, 3, 1, 1, 3, 2, 0, 3, 0, 0, 3, 0, 0, 3, 2, 3,
       3, 2, 1, 3, 3, 2, 3, 1, 2, 1, 2, 0, 2, 3, 1,